import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';

import { ResultspanelComponent } from './resultspanel.component';

describe('ResultspanelComponent', () => {
  let component: ResultspanelComponent;
  let fixture: ComponentFixture<ResultspanelComponent>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [ ResultspanelComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(ResultspanelComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

/* testing the filtering functions */
describe('filterDataForCountySelection', () => {
  let component: ResultspanelComponent;
  let fixture: ComponentFixture<ResultspanelComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ResultspanelComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(ResultspanelComponent);
    component = fixture.componentInstance;


    

        // Mock data for items
        component.items = [
          {
            FIPS: '56001',
              "ID": 1,
              "destindx": 1,
              "tract_id": 1,
              "BASE_FINAL_PM": 1,
              "CTRL_FINAL_PM": 1,
              "DELTA_FINAL_PM": 1,
              "BASE_FINAL_O3": 1,
              "CTRL_FINAL_O3": 1,
              "DELTA_FINAL_O3": 1,
              "PM_HA_All_Respiratory": 1,
              "PM_Acute_Myocardial_Infarction_Nonfatal": 1,
              "PM_Minor_Restricted_Activity_Days": 1,
              "PM_Mortality_All_Cause__low_": 1,
              "PM_Mortality_All_Cause__high_": 1,
              "PM_Infant_Mortality": 1,
              "PM_Work_Loss_Days": 1,
              "PM_Incidence_Lung_Cancer": 1,
              "PM_Incidence_Hay_Fever_Rhinitis": 1,
              "PM_Incidence_Asthma": 1,
              "PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "PM_HA_Alzheimers_Disease": 1,
              "PM_HA_Parkinsons_Disease": 1,
              "PM_Incidence_Stroke": 1,
              "PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "PM_Asthma_Symptoms_Albuterol_use": 1,
              "PM_HA_Respiratory2": 1,
              "PM_ER_visits_respiratory": 1,
              "PM_ER_visits_All_Cardiac_Outcomes": 1,
              "O3_ER_visits_respiratory": 1,
              "O3_HA_All_Respiratory": 1,
              "O3_Incidence_Hay_Fever_Rhinitis": 1,
              "O3_Incidence_Asthma": 1,
              "O3_Asthma_Symptoms_Chest_Tightness": 1,
              "O3_Asthma_Symptoms_Cough": 1,
              "O3_Asthma_Symptoms_Shortness_of_Breath": 1,
              "O3_Asthma_Symptoms_Wheeze": 1,
              "O3_ER_Visits_Asthma": 1,
              "O3_School_Loss_Days": 1,
              "O3_Mortality_Longterm_exposure": 1,
              "O3_Mortality_Shortterm_exposure": 1,
              "C__PM_Acute_Myocardial_Infarction_Nonfatal": 1,
              "C__PM_Resp_Hosp_Adm": 1,
              "C__PM_Minor_Restricted_Activity_Days": 1,
              "C__PM_Mortality_All_Cause__low_": 1,
              "C__PM_Mortality_All_Cause__high_": 1,
              "C__PM_Infant_Mortality": 1,
              "C__PM_Work_Loss_Days": 1,
              "C__PM_Incidence_Lung_Cancer": 1,
              "C__PM_Incidence_Hay_Fever_Rhinitis": 1,
              "C__PM_Incidence_Asthma": 1,
              "C__PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "C__PM_HA_Alzheimers_Disease": 1,
              "C__PM_HA_Parkinsons_Disease": 1,
              "C__PM_Incidence_Stroke": 1,
              "C__PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "C__PM_Asthma_Symptoms_Albuterol_use": 1,
              "C__PM_HA_Respiratory2": 1,
              "C__PM_ER_visits_respiratory": 1,
              "C__PM_ER_visits_All_Cardiac_Outcomes": 1,
              "C__O3_ER_visits_respiratory": 1,
              "C__O3_HA_All_Respiratory": 1,
              "C__O3_Incidence_Hay_Fever_Rhinitis": 1,
              "C__O3_Incidence_Asthma": 1,
              "C__O3_Asthma_Symptoms_Chest_Tightness": 1,
              "C__O3_Asthma_Symptoms_Cough": 1,
              "C__O3_Asthma_Symptoms_Shortness_of_Breath": 1,
              "C__O3_Asthma_Symptoms_Wheeze": 1,
              "C__O3_ER_Visits_Asthma": 1,
              "C__O3_School_Loss_Days": 1,
              "C__O3_Mortality_Longterm_exposure": 1,
              "C__O3_Mortality_Shortterm_exposure": 1,
              "C__Total_Health_Benefits_Low_Value": 1,
              "C__Total_Health_Benefits_High_Value": 1,
              "C__Total_PM_Low_Value": 1,
              "C__Total_PM_High_Value": 1,
              "C__Total_O3_Value": 1,
              "STATE": 1,
              "COUNTY": 1,
              "IRA_fraction": 1,
              "CJEST": 1,
              "Acute_Myocardial_Infarction_Nonfatal": 1,
              "Minor_Restricted_Activity_Days": 1,
              "Infant_Mortality": 1,
              "Work_Loss_Days": 1,
              "Incidence_Lung_Cancer": 1,
              "HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "HA_Alzheimers_Disease": 1,
              "HA_Parkinsons_Disease": 1,
              "Incidence_Stroke": 1,
              "Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "ER_visits_All_Cardiac_Outcomes": 1,
              "ER_Visits_Asthma": 1,
              "School_Loss_Days": 1,
              "C__Acute_Myocardial_Infarction_Nonfatal": 1,
              "C__Minor_Restricted_Activity_Days": 1,
              "C__Infant_Mortality": 1,
              "C__Work_Loss_Days": 1,
              "C__Incidence_Lung_Cancer": 1,
              "C__HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "C__HA_Alzheimers_Disease": 1,
              "C__HA_Parkinsons_Disease": 1,
              "C__Incidence_Stroke": 1,
              "C__Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "C__ER_visits_All_Cardiac_Outcomes": 1,
              "C__ER_Visits_Asthma": 1,
              "C__School_Loss_Days": 1,
              "C__Total_Low_Value": 1,
              "C__Total_High_Value": 1,
              "C__Total_Value": 1,
              "HA_All_Respiratory": 1,
              "C__HA_All_Respiratory": 1,
              "Mortality_All_Cause__low_": 1,
              "C__Mortality_All_Cause__low_": 1,
              "Mortality_All_Cause__high_": 1,
              "C__Mortality_All_Cause__high_": 1,
              "Asthma_Symptoms": 1,
              "C__Asthma_Symptoms": 1,
              "Incidence_Hay_Fever_Rhinitis": 1,
              "C__Incidence_Hay_Fever_Rhinitis": 1,
              "Incidence_Asthma": 1,
              "C__Incidence_Asthma": 1,
              "ER_visits_respiratory": 1,
              "C__ER_visits_respiratory": 1
          },
          {
            FIPS: '56002',
              "ID": 1,
              "destindx": 1,
              "tract_id": 1,
              "BASE_FINAL_PM": 1,
              "CTRL_FINAL_PM": 1,
              "DELTA_FINAL_PM": 1,
              "BASE_FINAL_O3": 1,
              "CTRL_FINAL_O3": 1,
              "DELTA_FINAL_O3": 1,
              "PM_HA_All_Respiratory": 1,
              "PM_Acute_Myocardial_Infarction_Nonfatal": 1,
              "PM_Minor_Restricted_Activity_Days": 1,
              "PM_Mortality_All_Cause__low_": 1,
              "PM_Mortality_All_Cause__high_": 1,
              "PM_Infant_Mortality": 1,
              "PM_Work_Loss_Days": 1,
              "PM_Incidence_Lung_Cancer": 1,
              "PM_Incidence_Hay_Fever_Rhinitis": 1,
              "PM_Incidence_Asthma": 1,
              "PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "PM_HA_Alzheimers_Disease": 1,
              "PM_HA_Parkinsons_Disease": 1,
              "PM_Incidence_Stroke": 1,
              "PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "PM_Asthma_Symptoms_Albuterol_use": 1,
              "PM_HA_Respiratory2": 1,
              "PM_ER_visits_respiratory": 1,
              "PM_ER_visits_All_Cardiac_Outcomes": 1,
              "O3_ER_visits_respiratory": 1,
              "O3_HA_All_Respiratory": 1,
              "O3_Incidence_Hay_Fever_Rhinitis": 1,
              "O3_Incidence_Asthma": 1,
              "O3_Asthma_Symptoms_Chest_Tightness": 1,
              "O3_Asthma_Symptoms_Cough": 1,
              "O3_Asthma_Symptoms_Shortness_of_Breath": 1,
              "O3_Asthma_Symptoms_Wheeze": 1,
              "O3_ER_Visits_Asthma": 1,
              "O3_School_Loss_Days": 1,
              "O3_Mortality_Longterm_exposure": 1,
              "O3_Mortality_Shortterm_exposure": 1,
              "C__PM_Acute_Myocardial_Infarction_Nonfatal": 1,
              "C__PM_Resp_Hosp_Adm": 1,
              "C__PM_Minor_Restricted_Activity_Days": 1,
              "C__PM_Mortality_All_Cause__low_": 1,
              "C__PM_Mortality_All_Cause__high_": 1,
              "C__PM_Infant_Mortality": 1,
              "C__PM_Work_Loss_Days": 1,
              "C__PM_Incidence_Lung_Cancer": 1,
              "C__PM_Incidence_Hay_Fever_Rhinitis": 1,
              "C__PM_Incidence_Asthma": 1,
              "C__PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "C__PM_HA_Alzheimers_Disease": 1,
              "C__PM_HA_Parkinsons_Disease": 1,
              "C__PM_Incidence_Stroke": 1,
              "C__PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "C__PM_Asthma_Symptoms_Albuterol_use": 1,
              "C__PM_HA_Respiratory2": 1,
              "C__PM_ER_visits_respiratory": 1,
              "C__PM_ER_visits_All_Cardiac_Outcomes": 1,
              "C__O3_ER_visits_respiratory": 1,
              "C__O3_HA_All_Respiratory": 1,
              "C__O3_Incidence_Hay_Fever_Rhinitis": 1,
              "C__O3_Incidence_Asthma": 1,
              "C__O3_Asthma_Symptoms_Chest_Tightness": 1,
              "C__O3_Asthma_Symptoms_Cough": 1,
              "C__O3_Asthma_Symptoms_Shortness_of_Breath": 1,
              "C__O3_Asthma_Symptoms_Wheeze": 1,
              "C__O3_ER_Visits_Asthma": 1,
              "C__O3_School_Loss_Days": 1,
              "C__O3_Mortality_Longterm_exposure": 1,
              "C__O3_Mortality_Shortterm_exposure": 1,
              "C__Total_Health_Benefits_Low_Value": 1,
              "C__Total_Health_Benefits_High_Value": 1,
              "C__Total_PM_Low_Value": 1,
              "C__Total_PM_High_Value": 1,
              "C__Total_O3_Value": 1,
              "STATE": 1,
              "COUNTY": 1,
              "IRA_fraction": 1,
              "CJEST": 1,
              "Acute_Myocardial_Infarction_Nonfatal": 1,
              "Minor_Restricted_Activity_Days": 1,
              "Infant_Mortality": 1,
              "Work_Loss_Days": 1,
              "Incidence_Lung_Cancer": 1,
              "HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "HA_Alzheimers_Disease": 1,
              "HA_Parkinsons_Disease": 1,
              "Incidence_Stroke": 1,
              "Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "ER_visits_All_Cardiac_Outcomes": 1,
              "ER_Visits_Asthma": 1,
              "School_Loss_Days": 1,
              "C__Acute_Myocardial_Infarction_Nonfatal": 1,
              "C__Minor_Restricted_Activity_Days": 1,
              "C__Infant_Mortality": 1,
              "C__Work_Loss_Days": 1,
              "C__Incidence_Lung_Cancer": 1,
              "C__HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
              "C__HA_Alzheimers_Disease": 1,
              "C__HA_Parkinsons_Disease": 1,
              "C__Incidence_Stroke": 1,
              "C__Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
              "C__ER_visits_All_Cardiac_Outcomes": 1,
              "C__ER_Visits_Asthma": 1,
              "C__School_Loss_Days": 1,
              "C__Total_Low_Value": 1,
              "C__Total_High_Value": 1,
              "C__Total_Value": 1,
              "HA_All_Respiratory": 1,
              "C__HA_All_Respiratory": 1,
              "Mortality_All_Cause__low_": 1,
              "C__Mortality_All_Cause__low_": 1,
              "Mortality_All_Cause__high_": 1,
              "C__Mortality_All_Cause__high_": 1,
              "Asthma_Symptoms": 1,
              "C__Asthma_Symptoms": 1,
              "Incidence_Hay_Fever_Rhinitis": 1,
              "C__Incidence_Hay_Fever_Rhinitis": 1,
              "Incidence_Asthma": 1,
              "C__Incidence_Asthma": 1,
              "ER_visits_respiratory": 1,
              "C__ER_visits_respiratory": 1
            },
            {
              FIPS: '56003',
                "ID": 1,
                "destindx": 1,
                "tract_id": 1,
                "BASE_FINAL_PM": 1,
                "CTRL_FINAL_PM": 1,
                "DELTA_FINAL_PM": 1,
                "BASE_FINAL_O3": 1,
                "CTRL_FINAL_O3": 1,
                "DELTA_FINAL_O3": 1,
                "PM_HA_All_Respiratory": 1,
                "PM_Acute_Myocardial_Infarction_Nonfatal": 1,
                "PM_Minor_Restricted_Activity_Days": 1,
                "PM_Mortality_All_Cause__low_": 1,
                "PM_Mortality_All_Cause__high_": 1,
                "PM_Infant_Mortality": 1,
                "PM_Work_Loss_Days": 1,
                "PM_Incidence_Lung_Cancer": 1,
                "PM_Incidence_Hay_Fever_Rhinitis": 1,
                "PM_Incidence_Asthma": 1,
                "PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                "PM_HA_Alzheimers_Disease": 1,
                "PM_HA_Parkinsons_Disease": 1,
                "PM_Incidence_Stroke": 1,
                "PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                "PM_Asthma_Symptoms_Albuterol_use": 1,
                "PM_HA_Respiratory2": 1,
                "PM_ER_visits_respiratory": 1,
                "PM_ER_visits_All_Cardiac_Outcomes": 1,
                "O3_ER_visits_respiratory": 1,
                "O3_HA_All_Respiratory": 1,
                "O3_Incidence_Hay_Fever_Rhinitis": 1,
                "O3_Incidence_Asthma": 1,
                "O3_Asthma_Symptoms_Chest_Tightness": 1,
                "O3_Asthma_Symptoms_Cough": 1,
                "O3_Asthma_Symptoms_Shortness_of_Breath": 1,
                "O3_Asthma_Symptoms_Wheeze": 1,
                "O3_ER_Visits_Asthma": 1,
                "O3_School_Loss_Days": 1,
                "O3_Mortality_Longterm_exposure": 1,
                "O3_Mortality_Shortterm_exposure": 1,
                "C__PM_Acute_Myocardial_Infarction_Nonfatal": 1,
                "C__PM_Resp_Hosp_Adm": 1,
                "C__PM_Minor_Restricted_Activity_Days": 1,
                "C__PM_Mortality_All_Cause__low_": 1,
                "C__PM_Mortality_All_Cause__high_": 1,
                "C__PM_Infant_Mortality": 1,
                "C__PM_Work_Loss_Days": 1,
                "C__PM_Incidence_Lung_Cancer": 1,
                "C__PM_Incidence_Hay_Fever_Rhinitis": 1,
                "C__PM_Incidence_Asthma": 1,
                "C__PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                "C__PM_HA_Alzheimers_Disease": 1,
                "C__PM_HA_Parkinsons_Disease": 1,
                "C__PM_Incidence_Stroke": 1,
                "C__PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                "C__PM_Asthma_Symptoms_Albuterol_use": 1,
                "C__PM_HA_Respiratory2": 1,
                "C__PM_ER_visits_respiratory": 1,
                "C__PM_ER_visits_All_Cardiac_Outcomes": 1,
                "C__O3_ER_visits_respiratory": 1,
                "C__O3_HA_All_Respiratory": 1,
                "C__O3_Incidence_Hay_Fever_Rhinitis": 1,
                "C__O3_Incidence_Asthma": 1,
                "C__O3_Asthma_Symptoms_Chest_Tightness": 1,
                "C__O3_Asthma_Symptoms_Cough": 1,
                "C__O3_Asthma_Symptoms_Shortness_of_Breath": 1,
                "C__O3_Asthma_Symptoms_Wheeze": 1,
                "C__O3_ER_Visits_Asthma": 1,
                "C__O3_School_Loss_Days": 1,
                "C__O3_Mortality_Longterm_exposure": 1,
                "C__O3_Mortality_Shortterm_exposure": 1,
                "C__Total_Health_Benefits_Low_Value": 1,
                "C__Total_Health_Benefits_High_Value": 1,
                "C__Total_PM_Low_Value": 1,
                "C__Total_PM_High_Value": 1,
                "C__Total_O3_Value": 1,
                "STATE": 1,
                "COUNTY": 1,
                "IRA_fraction": 1,
                "CJEST": 1,
                "Acute_Myocardial_Infarction_Nonfatal": 1,
                "Minor_Restricted_Activity_Days": 1,
                "Infant_Mortality": 1,
                "Work_Loss_Days": 1,
                "Incidence_Lung_Cancer": 1,
                "HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                "HA_Alzheimers_Disease": 1,
                "HA_Parkinsons_Disease": 1,
                "Incidence_Stroke": 1,
                "Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                "ER_visits_All_Cardiac_Outcomes": 1,
                "ER_Visits_Asthma": 1,
                "School_Loss_Days": 1,
                "C__Acute_Myocardial_Infarction_Nonfatal": 1,
                "C__Minor_Restricted_Activity_Days": 1,
                "C__Infant_Mortality": 1,
                "C__Work_Loss_Days": 1,
                "C__Incidence_Lung_Cancer": 1,
                "C__HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                "C__HA_Alzheimers_Disease": 1,
                "C__HA_Parkinsons_Disease": 1,
                "C__Incidence_Stroke": 1,
                "C__Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                "C__ER_visits_All_Cardiac_Outcomes": 1,
                "C__ER_Visits_Asthma": 1,
                "C__School_Loss_Days": 1,
                "C__Total_Low_Value": 1,
                "C__Total_High_Value": 1,
                "C__Total_Value": 1,
                "HA_All_Respiratory": 1,
                "C__HA_All_Respiratory": 1,
                "Mortality_All_Cause__low_": 1,
                "C__Mortality_All_Cause__low_": 1,
                "Mortality_All_Cause__high_": 1,
                "C__Mortality_All_Cause__high_": 1,
                "Asthma_Symptoms": 1,
                "C__Asthma_Symptoms": 1,
                "Incidence_Hay_Fever_Rhinitis": 1,
                "C__Incidence_Hay_Fever_Rhinitis": 1,
                "Incidence_Asthma": 1,
                "C__Incidence_Asthma": 1,
                "ER_visits_respiratory": 1,
                "C__ER_visits_respiratory": 1
              },
              {
                FIPS: '57003',
                  "ID": 1,
                  "destindx": 1,
                  "tract_id": 1,
                  "BASE_FINAL_PM": 1,
                  "CTRL_FINAL_PM": 1,
                  "DELTA_FINAL_PM": 1,
                  "BASE_FINAL_O3": 1,
                  "CTRL_FINAL_O3": 1,
                  "DELTA_FINAL_O3": 1,
                  "PM_HA_All_Respiratory": 1,
                  "PM_Acute_Myocardial_Infarction_Nonfatal": 1,
                  "PM_Minor_Restricted_Activity_Days": 1,
                  "PM_Mortality_All_Cause__low_": 1,
                  "PM_Mortality_All_Cause__high_": 1,
                  "PM_Infant_Mortality": 1,
                  "PM_Work_Loss_Days": 1,
                  "PM_Incidence_Lung_Cancer": 1,
                  "PM_Incidence_Hay_Fever_Rhinitis": 1,
                  "PM_Incidence_Asthma": 1,
                  "PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                  "PM_HA_Alzheimers_Disease": 1,
                  "PM_HA_Parkinsons_Disease": 1,
                  "PM_Incidence_Stroke": 1,
                  "PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                  "PM_Asthma_Symptoms_Albuterol_use": 1,
                  "PM_HA_Respiratory2": 1,
                  "PM_ER_visits_respiratory": 1,
                  "PM_ER_visits_All_Cardiac_Outcomes": 1,
                  "O3_ER_visits_respiratory": 1,
                  "O3_HA_All_Respiratory": 1,
                  "O3_Incidence_Hay_Fever_Rhinitis": 1,
                  "O3_Incidence_Asthma": 1,
                  "O3_Asthma_Symptoms_Chest_Tightness": 1,
                  "O3_Asthma_Symptoms_Cough": 1,
                  "O3_Asthma_Symptoms_Shortness_of_Breath": 1,
                  "O3_Asthma_Symptoms_Wheeze": 1,
                  "O3_ER_Visits_Asthma": 1,
                  "O3_School_Loss_Days": 1,
                  "O3_Mortality_Longterm_exposure": 1,
                  "O3_Mortality_Shortterm_exposure": 1,
                  "C__PM_Acute_Myocardial_Infarction_Nonfatal": 1,
                  "C__PM_Resp_Hosp_Adm": 1,
                  "C__PM_Minor_Restricted_Activity_Days": 1,
                  "C__PM_Mortality_All_Cause__low_": 1,
                  "C__PM_Mortality_All_Cause__high_": 1,
                  "C__PM_Infant_Mortality": 1,
                  "C__PM_Work_Loss_Days": 1,
                  "C__PM_Incidence_Lung_Cancer": 1,
                  "C__PM_Incidence_Hay_Fever_Rhinitis": 1,
                  "C__PM_Incidence_Asthma": 1,
                  "C__PM_HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                  "C__PM_HA_Alzheimers_Disease": 1,
                  "C__PM_HA_Parkinsons_Disease": 1,
                  "C__PM_Incidence_Stroke": 1,
                  "C__PM_Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                  "C__PM_Asthma_Symptoms_Albuterol_use": 1,
                  "C__PM_HA_Respiratory2": 1,
                  "C__PM_ER_visits_respiratory": 1,
                  "C__PM_ER_visits_All_Cardiac_Outcomes": 1,
                  "C__O3_ER_visits_respiratory": 1,
                  "C__O3_HA_All_Respiratory": 1,
                  "C__O3_Incidence_Hay_Fever_Rhinitis": 1,
                  "C__O3_Incidence_Asthma": 1,
                  "C__O3_Asthma_Symptoms_Chest_Tightness": 1,
                  "C__O3_Asthma_Symptoms_Cough": 1,
                  "C__O3_Asthma_Symptoms_Shortness_of_Breath": 1,
                  "C__O3_Asthma_Symptoms_Wheeze": 1,
                  "C__O3_ER_Visits_Asthma": 1,
                  "C__O3_School_Loss_Days": 1,
                  "C__O3_Mortality_Longterm_exposure": 1,
                  "C__O3_Mortality_Shortterm_exposure": 1,
                  "C__Total_Health_Benefits_Low_Value": 1,
                  "C__Total_Health_Benefits_High_Value": 1,
                  "C__Total_PM_Low_Value": 1,
                  "C__Total_PM_High_Value": 1,
                  "C__Total_O3_Value": 1,
                  "STATE": 1,
                  "COUNTY": 1,
                  "IRA_fraction": 1,
                  "CJEST": 1,
                  "Acute_Myocardial_Infarction_Nonfatal": 1,
                  "Minor_Restricted_Activity_Days": 1,
                  "Infant_Mortality": 1,
                  "Work_Loss_Days": 1,
                  "Incidence_Lung_Cancer": 1,
                  "HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                  "HA_Alzheimers_Disease": 1,
                  "HA_Parkinsons_Disease": 1,
                  "Incidence_Stroke": 1,
                  "Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                  "ER_visits_All_Cardiac_Outcomes": 1,
                  "ER_Visits_Asthma": 1,
                  "School_Loss_Days": 1,
                  "C__Acute_Myocardial_Infarction_Nonfatal": 1,
                  "C__Minor_Restricted_Activity_Days": 1,
                  "C__Infant_Mortality": 1,
                  "C__Work_Loss_Days": 1,
                  "C__Incidence_Lung_Cancer": 1,
                  "C__HA_Cardio_Cerebro_and_Peripheral_Vascular_Disease": 1,
                  "C__HA_Alzheimers_Disease": 1,
                  "C__HA_Parkinsons_Disease": 1,
                  "C__Incidence_Stroke": 1,
                  "C__Incidence_Out_of_Hospital_Cardiac_Arrest": 1,
                  "C__ER_visits_All_Cardiac_Outcomes": 1,
                  "C__ER_Visits_Asthma": 1,
                  "C__School_Loss_Days": 1,
                  "C__Total_Low_Value": 1,
                  "C__Total_High_Value": 1,
                  "C__Total_Value": 1,
                  "HA_All_Respiratory": 1,
                  "C__HA_All_Respiratory": 1,
                  "Mortality_All_Cause__low_": 1,
                  "C__Mortality_All_Cause__low_": 1,
                  "Mortality_All_Cause__high_": 1,
                  "C__Mortality_All_Cause__high_": 1,
                  "Asthma_Symptoms": 1,
                  "C__Asthma_Symptoms": 1,
                  "Incidence_Hay_Fever_Rhinitis": 1,
                  "C__Incidence_Hay_Fever_Rhinitis": 1,
                  "Incidence_Asthma": 1,
                  "C__Incidence_Asthma": 1,
                  "ER_visits_respiratory": 1,
                  "C__ER_visits_respiratory": 1
                },
        ];
      });
    
      it('should validate that state-level and county-level results match', () => {
        // Set filtervalue for state-level filtering
        component.filtervalue = '56';
    
        // Call filterDataForStateSelection() to compute state-level sums
        component.filterDataForStateSelection();
        const stateLevelResults = {
          TotalHealthBenefitsValue_high: component.TotalHealthBenefitsValue_high,
          TotalHealthBenefitsValue_low: component.TotalHealthBenefitsValue_low,
        
          TotalPM_high: component.TotalPM_high,
          TotalPM_low: component.TotalPM_low,
          TotalO3: component.TotalO3,
        
          Mortality_low: component.Mortality_low,
          MortalityValue_low: component.MortalityValue_low,
        
          MortalityValue_high: component.MortalityValue_high,
          Mortality_high: component.Mortality_high,
        
          PM_Mortality_low: component.PM_Mortality_low,
          PM_Mortality_high: component.PM_Mortality_high,
          PM_MortalityValue_low: component.PM_MortalityValue_low,
          PM_MortalityValue_high: component.PM_MortalityValue_high,
        
          O3_Mortality_long: component.O3_Mortality_long,
          O3_Mortality_short: component.O3_Mortality_short,
          O3_MortalityValue_long: component.O3_MortalityValue_long,
          O3_MortalityValue_short: component.O3_MortalityValue_short,
        
          NonfatalHeartAttacks: component.NonfatalHeartAttacks,
          NonfatalHeartAttacksValue: component.NonfatalHeartAttacksValue,
        
          InfantMortality: component.InfantMortality,
          InfantMortalityValue: component.InfantMortalityValue,
        
          HospitalAdmitsAllRespiratory: component.HospitalAdmitsAllRespiratory,
          HospitalAdmitsAllRespiratoryValue: component.HospitalAdmitsAllRespiratoryValue,
        
          PMHospitalAdmitsAllRespiratory: component.PMHospitalAdmitsAllRespiratory,
          PMHospitalAdmitsAllRespiratoryValue: component.PMHospitalAdmitsAllRespiratoryValue,
        
          O3HospitalAdmitsAllRespiratory: component.O3HospitalAdmitsAllRespiratory,
          O3HospitalAdmitsAllRespiratoryValue: component.O3HospitalAdmitsAllRespiratoryValue,
        
          EmergencyRoomVisitsAsthma: component.EmergencyRoomVisitsAsthma,
          EmergencyRoomVisitsAsthmaValue: component.EmergencyRoomVisitsAsthmaValue,
        
          MinorRestrictedActivityDays: component.MinorRestrictedActivityDays,
          MinorRestrictedActivityDaysValue: component.MinorRestrictedActivityDaysValue,
        
          HospitalAdmitsAlzheimersDisease: component.HospitalAdmitsAlzheimersDisease,
          HospitalAdmitsAlzheimersDiseaseValue: component.HospitalAdmitsAlzheimersDiseaseValue,
        
          HospitalAdmitsParkinsonsDisease: component.HospitalAdmitsParkinsonsDisease,
          HospitalAdmitsParkinsonsDiseaseValue: component.HospitalAdmitsParkinsonsDiseaseValue,
        
          IncidenceStroke: component.IncidenceStroke,
          IncidenceStrokeValue: component.IncidenceStrokeValue,
        
          IncidenceOutOfHospitalCardiacArrest: component.IncidenceOutOfHospitalCardiacArrest,
          IncidenceOutOfHospitalCardiacArrestValue: component.IncidenceOutOfHospitalCardiacArrestValue,
        
          IncidenceAsthma: component.IncidenceAsthma,
          IncidenceAsthmaValue: component.IncidenceAsthmaValue,
        
          PMIncidenceAsthma: component.PMIncidenceAsthma,
          PMIncidenceAsthmaValue: component.PMIncidenceAsthmaValue,
          O3IncidenceAsthma: component.O3IncidenceAsthma,
          O3IncidenceAsthmaValue: component.O3IncidenceAsthmaValue,
        
          AsthmaSymptoms: component.AsthmaSymptoms,
          AsthmaSymptomsValue: component.AsthmaSymptomsValue,
          AlbuterolUse: component.AlbuterolUse,
          AlbuterolUseValue: component.AlbuterolUseValue,
          Cough: component.Cough,
          CoughValue: component.CoughValue,
          ChestTightness: component.ChestTightness,
          ChestTightnessValue: component.ChestTightnessValue,
          ShortnessOfBreath: component.ShortnessOfBreath,
          ShortnessOfBreathValue: component.ShortnessOfBreathValue,
          Wheeze: component.Wheeze,
          WheezeValue: component.WheezeValue,
        
          IncidenceHayFeverRhinitis: component.IncidenceHayFeverRhinitis,
          IncidenceHayFeverRhinitisValue: component.IncidenceHayFeverRhinitisValue,
          PMIncidenceHayFeverRhinitis: component.PMIncidenceHayFeverRhinitis,
          PMIncidenceHayFeverRhinitisValue: component.PMIncidenceHayFeverRhinitisValue,
          O3IncidenceHayFeverRhinitis: component.O3IncidenceHayFeverRhinitis,
          O3IncidenceHayFeverRhinitisValue: component.O3IncidenceHayFeverRhinitisValue,
        
          HA_HCCPV_Disease: component.HA_HCCPV_Disease,
          HA_HCCPV_DiseaseValue: component.HA_HCCPV_DiseaseValue,
        
          IncidenceLungCancer: component.IncidenceLungCancer,
          IncidenceLungCancerValue: component.IncidenceLungCancerValue,
        
          ERVisitsAllCardiacOutcomes: component.ERVisitsAllCardiacOutcomes,
          ERVisitsAllCardiacOutcomesValue: component.ERVisitsAllCardiacOutcomesValue,
        
          ERVisitsAllRespiratory: component.ERVisitsAllRespiratory,
          ERVisitsAllRespiratoryValue: component.ERVisitsAllRespiratoryValue,
          PMERVisitsAllRespiratory: component.PMERVisitsAllRespiratory,
          PMERVisitsAllRespiratoryValue: component.PMERVisitsAllRespiratoryValue,
          O3ERVisitsAllRespiratory: component.O3ERVisitsAllRespiratory,
          O3ERVisitsAllRespiratoryValue: component.O3ERVisitsAllRespiratoryValue,
        
          SchoolLossDays: component.SchoolLossDays,
          SchoolLossDaysValue: component.SchoolLossDaysValue,
        
          WorkLossDays: component.WorkLossDays,
          WorkLossDaysValue: component.WorkLossDaysValue,
        };
    
        // Reset component properties to 0
        component.filtervalue = '56';
        Object.keys(stateLevelResults).forEach((key) => (component[key] = 0));
    
        // Call filterDataForCountySelection() for each matching FIPS and sum the results
        const countyLevelResults = { ...stateLevelResults }; // Start with empty sums
        Object.keys(countyLevelResults).forEach((key) => (countyLevelResults[key] = 0));
    
        component.items
          .filter((item) => item.FIPS.startsWith('56'))
          .forEach((item) => {
            component.filtervalue = item.FIPS;
            component.filterDataForCountySelection();
            Object.keys(countyLevelResults).forEach((key) => {
              countyLevelResults[key] += component[key];
            });
          });
    
        // Assert that state-level results match summed county-level results
        Object.keys(stateLevelResults).forEach((key) => {
          expect(stateLevelResults[key]).toBe(countyLevelResults[key]);
        });
      });
    });
