//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENSUS_DICT
    {
        public long census_index { get; set; }
        public string dest_tract { get; set; }
        public string FIPS { get; set; }
        public Nullable<long> destindx { get; set; }
        public Nullable<long> IRA { get; set; }
        public Nullable<long> CJEST { get; set; }
        public Nullable<double> IRA_fraction { get; set; }
    }
}
