//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Dict
    {
        public long ID { get; set; }
        public Nullable<long> SOURCEINDX { get; set; }
        public string FIPS { get; set; }
        public string STFIPS { get; set; }
        public string CNTYFIPS { get; set; }
        public string STNAME { get; set; }
        public string CYNAME { get; set; }
    }
}
