//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cobraEntities : DbContext
    {
        public cobraEntities()
            : base("name=cobraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_CR> SYS_CR { get; set; }
        public virtual DbSet<SYS_Destination> SYS_Destination { get; set; }
        public virtual DbSet<SYS_Dict> SYS_Dict { get; set; }
        public virtual DbSet<SYS_Emissions> SYS_Emissions { get; set; }
        public virtual DbSet<SYS_Emissions_Base> SYS_Emissions_Base { get; set; }
        public virtual DbSet<SYS_Emissions_Base_Summarized> SYS_Emissions_Base_Summarized { get; set; }
        public virtual DbSet<SYS_Emissions_Control> SYS_Emissions_Control { get; set; }
        public virtual DbSet<SYS_Emissions_Control_Summarized> SYS_Emissions_Control_Summarized { get; set; }
        public virtual DbSet<SYS_Emissions_Staging> SYS_Emissions_Staging { get; set; }
        public virtual DbSet<SYS_Incidence> SYS_Incidence { get; set; }
        public virtual DbSet<SYS_POP> SYS_POP { get; set; }
        public virtual DbSet<SYS_ScenarioEmissions_Staging> SYS_ScenarioEmissions_Staging { get; set; }
        public virtual DbSet<SYS_Srmatrix_2025> SYS_Srmatrix_2025 { get; set; }
        public virtual DbSet<SYS_Stacks> SYS_Stacks { get; set; }
        public virtual DbSet<SYS_SummarizedEmissions> SYS_SummarizedEmissions { get; set; }
        public virtual DbSet<SYS_Tiers> SYS_Tiers { get; set; }
        public virtual DbSet<SYS_Valuation> SYS_Valuation { get; set; }
        public virtual DbSet<SYS_voc2soa> SYS_voc2soa { get; set; }
        public virtual DbSet<SYS_Results> SYS_Results { get; set; }
    }
}
