//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Srmatrix_2025
    {
        public long ID { get; set; }
        public Nullable<long> typeindx { get; set; }
        public Nullable<long> sourceindx { get; set; }
        public Nullable<long> destindx { get; set; }
        public Nullable<double> c_PM25 { get; set; }
        public Nullable<double> c_NO3 { get; set; }
        public Nullable<double> c_SO4 { get; set; }
        public Nullable<double> tx_nh3 { get; set; }
    }
}
