//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CR
    {
        public long ID { get; set; }
        public Nullable<long> FunctionID { get; set; }
        public string Endpoint { get; set; }
        public Nullable<double> PoolingWeight { get; set; }
        public string Seasonal_Metric { get; set; }
        public string Study_Author { get; set; }
        public Nullable<long> Study_Year { get; set; }
        public Nullable<long> Start_Age { get; set; }
        public Nullable<long> End_Age { get; set; }
        public string Function { get; set; }
        public Nullable<double> Beta { get; set; }
        public string Adjusted { get; set; }
        public Nullable<double> Parameter_1_Beta { get; set; }
        public Nullable<double> A { get; set; }
        public string Name_A { get; set; }
        public Nullable<double> B { get; set; }
        public string Name_B { get; set; }
        public Nullable<double> C { get; set; }
        public string Name_C { get; set; }
        public Nullable<long> Cases { get; set; }
        public string IncidenceEndpoint { get; set; }
    }
}
