//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_POP
    {
        public long ID { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> DestinationID { get; set; }
        public Nullable<long> FIPS { get; set; }
        public Nullable<double> Age0 { get; set; }
        public Nullable<double> Age1 { get; set; }
        public Nullable<double> Age2 { get; set; }
        public Nullable<double> Age3 { get; set; }
        public Nullable<double> Age4 { get; set; }
        public Nullable<double> Age5 { get; set; }
        public Nullable<double> Age6 { get; set; }
        public Nullable<double> Age7 { get; set; }
        public Nullable<double> Age8 { get; set; }
        public Nullable<double> Age9 { get; set; }
        public Nullable<double> Age10 { get; set; }
        public Nullable<double> Age11 { get; set; }
        public Nullable<double> Age12 { get; set; }
        public Nullable<double> Age13 { get; set; }
        public Nullable<double> Age14 { get; set; }
        public Nullable<double> Age15 { get; set; }
        public Nullable<double> Age16 { get; set; }
        public Nullable<double> Age17 { get; set; }
        public Nullable<double> Age18 { get; set; }
        public Nullable<double> Age19 { get; set; }
        public Nullable<double> Age20 { get; set; }
        public Nullable<double> Age21 { get; set; }
        public Nullable<double> Age22 { get; set; }
        public Nullable<double> Age23 { get; set; }
        public Nullable<double> Age24 { get; set; }
        public Nullable<double> Age25 { get; set; }
        public Nullable<double> Age26 { get; set; }
        public Nullable<double> Age27 { get; set; }
        public Nullable<double> Age28 { get; set; }
        public Nullable<double> Age29 { get; set; }
        public Nullable<double> Age30 { get; set; }
        public Nullable<double> Age31 { get; set; }
        public Nullable<double> Age32 { get; set; }
        public Nullable<double> Age33 { get; set; }
        public Nullable<double> Age34 { get; set; }
        public Nullable<double> Age35 { get; set; }
        public Nullable<double> Age36 { get; set; }
        public Nullable<double> Age37 { get; set; }
        public Nullable<double> Age38 { get; set; }
        public Nullable<double> Age39 { get; set; }
        public Nullable<double> Age40 { get; set; }
        public Nullable<double> Age41 { get; set; }
        public Nullable<double> Age42 { get; set; }
        public Nullable<double> Age43 { get; set; }
        public Nullable<double> Age44 { get; set; }
        public Nullable<double> Age45 { get; set; }
        public Nullable<double> Age46 { get; set; }
        public Nullable<double> Age47 { get; set; }
        public Nullable<double> Age48 { get; set; }
        public Nullable<double> Age49 { get; set; }
        public Nullable<double> Age50 { get; set; }
        public Nullable<double> Age51 { get; set; }
        public Nullable<double> Age52 { get; set; }
        public Nullable<double> Age53 { get; set; }
        public Nullable<double> Age54 { get; set; }
        public Nullable<double> Age55 { get; set; }
        public Nullable<double> Age56 { get; set; }
        public Nullable<double> Age57 { get; set; }
        public Nullable<double> Age58 { get; set; }
        public Nullable<double> Age59 { get; set; }
        public Nullable<double> Age60 { get; set; }
        public Nullable<double> Age61 { get; set; }
        public Nullable<double> Age62 { get; set; }
        public Nullable<double> Age63 { get; set; }
        public Nullable<double> Age64 { get; set; }
        public Nullable<double> Age65 { get; set; }
        public Nullable<double> Age66 { get; set; }
        public Nullable<double> Age67 { get; set; }
        public Nullable<double> Age68 { get; set; }
        public Nullable<double> Age69 { get; set; }
        public Nullable<double> Age70 { get; set; }
        public Nullable<double> Age71 { get; set; }
        public Nullable<double> Age72 { get; set; }
        public Nullable<double> Age73 { get; set; }
        public Nullable<double> Age74 { get; set; }
        public Nullable<double> Age75 { get; set; }
        public Nullable<double> Age76 { get; set; }
        public Nullable<double> Age77 { get; set; }
        public Nullable<double> Age78 { get; set; }
        public Nullable<double> Age79 { get; set; }
        public Nullable<double> Age80 { get; set; }
        public Nullable<double> Age81 { get; set; }
        public Nullable<double> Age82 { get; set; }
        public Nullable<double> Age83 { get; set; }
        public Nullable<double> Age84 { get; set; }
        public Nullable<double> Age85 { get; set; }
        public Nullable<double> Age86 { get; set; }
        public Nullable<double> Age87 { get; set; }
        public Nullable<double> Age88 { get; set; }
        public Nullable<double> Age89 { get; set; }
        public Nullable<double> Age90 { get; set; }
        public Nullable<double> Age91 { get; set; }
        public Nullable<double> Age92 { get; set; }
        public Nullable<double> Age93 { get; set; }
        public Nullable<double> Age94 { get; set; }
        public Nullable<double> Age95 { get; set; }
        public Nullable<double> Age96 { get; set; }
        public Nullable<double> Age97 { get; set; }
        public Nullable<double> Age98 { get; set; }
        public Nullable<double> Age99 { get; set; }
    }
}
