//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Destination
    {
        public long ID { get; set; }
        public Nullable<long> destindx { get; set; }
        public Nullable<double> BASE_NOx { get; set; }
        public Nullable<double> BASE_SO2 { get; set; }
        public Nullable<double> BASE_NH3 { get; set; }
        public Nullable<double> BASE_SOA { get; set; }
        public Nullable<double> BASE_PM25 { get; set; }
        public Nullable<double> BASE_VOC { get; set; }
        public Nullable<double> BASE_O3N { get; set; }
        public Nullable<double> CTRL_NOx { get; set; }
        public Nullable<double> CTRL_SO2 { get; set; }
        public Nullable<double> CTRL_NH3 { get; set; }
        public Nullable<double> CTRL_SOA { get; set; }
        public Nullable<double> CTRL_PM25 { get; set; }
        public Nullable<double> CTRL_VOC { get; set; }
        public Nullable<double> CTRL_O3N { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> BASE_FINAL_PM { get; set; }
        public Nullable<double> CTRL_FINAL_PM { get; set; }
        public Nullable<double> DELTA_FINAL_PM { get; set; }
        public Nullable<double> BASE_FINAL_O3 { get; set; }
        public Nullable<double> CTRL_FINAL_O3 { get; set; }
        public Nullable<double> DELTA_FINAL_O3 { get; set; }
    }
}
