//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Emissions_Base
    {
        public long ID { get; set; }
        public Nullable<long> typeindx { get; set; }
        public Nullable<long> sourceindx { get; set; }
        public Nullable<long> stid { get; set; }
        public Nullable<long> cyid { get; set; }
        public Nullable<long> TIER1 { get; set; }
        public Nullable<long> TIER2 { get; set; }
        public Nullable<long> TIER3 { get; set; }
        public Nullable<double> NOx { get; set; }
        public Nullable<double> SO2 { get; set; }
        public Nullable<double> NH3 { get; set; }
        public Nullable<double> SOA { get; set; }
        public Nullable<double> PM25 { get; set; }
        public Nullable<double> VOC { get; set; }
    }
}
