//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobra_console.units
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Tiers
    {
        public long ID { get; set; }
        public Nullable<long> TIER1 { get; set; }
        public Nullable<long> TIER2 { get; set; }
        public Nullable<long> TIER3 { get; set; }
        public string TIER1NAME { get; set; }
        public string TIER2NAME { get; set; }
        public string TIER3NAME { get; set; }
    }
}
