user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 4096;  # Allows more simultaneous requests
    multi_accept on;  
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Increase timeouts to handle large uploads
    client_body_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    # Increase max client body size for uploads
    client_max_body_size 0;  # This allows unlimited upload size, change to a specific size if needed

    # Upstream configuration for MinIO servers
    upstream minio {
    	least_conn;  # Ensures requests go to the least busy MinIO server
    	server minio1:9000 max_fails=3 fail_timeout=30s;
    	server minio2:9000 max_fails=3 fail_timeout=30s;
    	server minio3:9000 max_fails=3 fail_timeout=30s;
    	server minio4:9000 max_fails=3 fail_timeout=30s;
}


    server {
        listen       9000;
        listen  [::]:9000;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        
        # To disable buffering
        proxy_buffering off;

        location / {
            # Pass headers
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Increase timeouts to handle large file uploads
            proxy_connect_timeout 300s;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;

            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "Keep-Alive";
	    proxy_set_header Keep-Alive "timeout=600";

            # Disable chunked transfer encoding
            chunked_transfer_encoding off;

            # Proxy pass to the upstream MinIO servers
            proxy_pass http://minio;
        }
    }
}
